export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_ROBROS_PENDING = "REQUEST_ROBROS_PENDING";
export const REQUEST_ROBROS_SUCCESS = "REQUEST_ROBROS_SUCCESS";
export const REQUEST_ROBROS_FAILED = "REQUEST_ROBROS_FAILED";
